apiVersion: apps/v1
kind: Deployment
metadata:
  name: securebank-app
  namespace: default
  labels:
    app: securebank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: securebank
  template:
    metadata:
      labels:
        app: securebank
    spec:
      containers:
      - name: securebank-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: securebank-service
  namespace: default
spec:
  selector:
    app: securebank
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
